const data={bases:{ally:{hp:2000,max:2000,x:90},enemy:{hp:1000,max:1000,x:10}},units:{red:{hp:300,atk:80,interval:1.2,speed:6,range:4.5,cost:50,cooldown:2.5,knockbacks:2},dog:{hp:200,atk:50,interval:1.4,speed:5,range:4,reward:40,knockbacks:1}},income:[{max:1000,rate:20,cost:100},{max:1200,rate:25,cost:150},{max:1400,rate:30,cost:200},{max:1600,rate:36,cost:300},{max:1800,rate:42,cost:400},{max:2000,rate:50,cost:null}]};
const $=s=>document.querySelector(s), unitsEl=$('#units');let game, last=0;
function reset(){game={money:100,level:0,units:[],enemyTimer:0,spawnCd:0,running:false,ended:false,tutorial:0};data.bases.ally.hp=2000;data.bases.enemy.hp=1000;unitsEl.innerHTML='';$('#result').classList.add('hidden');tutorial();render();requestAnimationFrame(loop)}
function addUnit(type){let d=data.units[type], ally=type==='red';let u={type,ally,hp:d.hp,max:d.hp,x:ally?84:16,atkCd:0,kb:0};game.units.push(u);drawUnit(u);if(ally){game.money-=d.cost;game.spawnCd=d.cooldown;if(game.tutorial===2){game.tutorial=3;tutorial()}}}
function drawUnit(u){let e=document.createElement('div');e.className='unit '+(u.ally?'red':'dog');e.innerHTML='<div class="bar"><i></i></div>';u.el=e;unitsEl.append(e)}
function target(u){let foes=game.units.filter(v=>v.ally!==u.ally);let dir=u.ally?-1:1;return foes.filter(v=>dir*(v.x-u.x)>=-1).sort((a,b)=>Math.abs(a.x-u.x)-Math.abs(b.x-u.x))[0]}
function damage(target,amount,from){target.hp-=amount;let pct=Math.max(0,target.hp/target.max)*100;target.el?.querySelector('i')?.style.setProperty('width',pct+'%');if(target.hp<=0){if(!target.ally)game.money+=data.units.dog.reward;target.el?.remove();game.units.splice(game.units.indexOf(target),1);return}let d=data.units[target.type];let threshold=target.max*(1-(target.kb+1)/(d.knockbacks+1));if(target.hp<=threshold&&target.kb<d.knockbacks){target.kb++;target.x+=target.ally?2:-2;target.el.classList.add('hit');setTimeout(()=>target.el?.classList.remove('hit'),120)}}
function attack(u,t){let d=data.units[u.type];u.atkCd=d.interval;if(t)damage(t,d.atk,u);else{let b=u.ally?data.bases.enemy:data.bases.ally;b.hp=Math.max(0,b.hp-d.atk);if(!b.hp)finish(u.ally)}}
function update(dt){game.money=Math.min(data.income[game.level].max,game.money+data.income[game.level].rate*dt);game.enemyTimer+=dt;if(game.enemyTimer>=5){game.enemyTimer-=5;addUnit('dog')}game.spawnCd=Math.max(0,game.spawnCd-dt);for(const u of [...game.units]){u.atkCd-=dt;let d=data.units[u.type],t=target(u),dist=t?Math.abs(t.x-u.x):Infinity;if(t&&dist<=d.range){if(u.atkCd<=0)attack(u,t)}else{let baseDist=u.ally?u.x-data.bases.enemy.x:data.bases.ally.x-u.x;if(!t&&baseDist<=d.range){if(u.atkCd<=0)attack(u)}else u.x+=(u.ally?-1:1)*d.speed*dt}u.x=Math.max(7,Math.min(93,u.x));u.el.style.left=`calc(${u.x}% - 21px)`}render()}
function render(){let l=data.income[game.level];$('#money').textContent=`${Math.floor(game.money)} / ${l.max}원`;$('#income').textContent=`수입 Lv.${game.level+1} · 초당 ${l.rate}원`;$('#enemyHp').textContent=`적 성 ${data.bases.enemy.hp} / ${data.bases.enemy.max}`;$('#allyHp').textContent=`아군 성 ${data.bases.ally.hp} / ${data.bases.ally.max}`;for(let [name,b] of Object.entries(data.bases))$(`#${name}Base span`).style.width=(b.hp/b.max*100)+'%';let sb=$('#spawnBtn'),ib=$('#incomeBtn'),canSpawn=game.running||game.tutorial===2,canUpgrade=game.running||game.tutorial===4;sb.disabled=game.money<data.units.red.cost||game.spawnCd>0||!canSpawn;sb.querySelector('em').style.display=game.spawnCd?'block':'none';sb.querySelector('em').style.transform=`scaleY(${game.spawnCd/data.units.red.cooldown})`;ib.disabled=!canUpgrade||game.level===5||game.money<(l.cost||0);ib.innerHTML=game.level===5?'수입 Lv.MAX':`수입 업그레이드<br><small>${l.cost}원</small>`}
function loop(t){let dt=Math.min(.05,(t-last)/1000||0);last=t;if(game&&!game.ended&&game.running)update(dt);if(game&&!game.ended)requestAnimationFrame(loop)}
function highlight(sel){document.querySelectorAll('.tutorial-target').forEach(e=>e.classList.remove('tutorial-target'));if(sel)$(sel).classList.add('tutorial-target')}
function tutorial(){let text=$('#tutorialText'),next=$('#nextBtn'),box=$('#tutorial');let steps=[['오른쪽은 아군의 성입니다.','#allyBase'],['왼쪽의 적 성을 파괴하면 승리합니다!','#enemyBase'],['돈을 사용해서 레드 동그라미를 출격시켜 보세요!','#spawnBtn'],['돈은 시간이 지나면 자동으로 모입니다. 적을 쓰러뜨려도 돈을 얻습니다!','#money'],['수입을 업그레이드하면 더 많은 돈을 더 빠르게 모을 수 있습니다!','#incomeBtn'],['캐릭터와 적은 자동으로 이동하고 공격합니다. 레드 동그라미를 계속 출격시켜 적 성을 파괴하세요!','']];if(game.tutorial>=steps.length){box.classList.add('hidden');highlight();game.running=true;return}box.classList.remove('hidden');text.textContent=steps[game.tutorial][0];highlight(steps[game.tutorial][1]);next.style.display=(game.tutorial===2||game.tutorial===4)?'none':'inline-block'}
$('#nextBtn').onclick=()=>{game.tutorial++;if(game.tutorial===4)game.money=Math.max(game.money,100);tutorial();render()};$('#spawnBtn').onclick=()=>addUnit('red');$('#incomeBtn').onclick=()=>{let l=data.income[game.level];if(game.money>=l.cost){game.money-=l.cost;game.level++;if(game.tutorial===4){game.tutorial++;tutorial()}render()}};function finish(win){game.ended=true;game.running=false;highlight();$('#result').classList.remove('hidden');$('#resultTitle').textContent=win?'한국 정복 완료!':'패배...'}$('#restartBtn').onclick=reset;reset();
